# "${}"" is replaced in 'with_env.lf' (build time)
# "{}" is replaced in the lambda (run time)

common:
  OUT_DIR: "${rootPath}/.out"
  TF_DIR: "${rootPath}/tf"
  AWS_REGION: us-east-1
  USERS_TABLE_NAME: users
  KEYWORDS_TABLE_NAME: keywords
  SEARCH_RESULTS_TABLE_NAME: search_results
  SEARCH_JOBS_QUEUE_TEMPLATE_NAME: "{socialMedia}_search_jobs"
  DISPATCH_SEARCH_JOBS_LAMBDA_NAME: dispatch_search_jobs
  SEARCH_TWITTER_LAMBDA_NAME: search_twitter
  API_ENDPOINT: https://r2iyq5t3oe.execute-api.us-east-1.amazonaws.com/api
  COGNITO_USER_POOL_ID: us-east-1_BGoxkHJoy
  COGNITO_CLIENT_ID: 3am3e9e4ho7r9timp1ejv91np9
  COGNITO_CLIENT_DOMAIN: https://thesocialwatcher.auth.us-east-1.amazoncognito.com
  SEARCH_RESULT_INDEX_VERSION: 1
  SYNC_SEARCH_RESULTS_TO_ES_LAMBDA_NAME: sync_search_results_to_es
  SYNC_SEARCH_RESULTS_TO_ES_QUEUE_URL: sync_search_results_to_es

local:
  DYNAMODB_PORT: 8000
  DYNAMODB_URL: http://localhost:8000
  MAIN_ELASTIC_SEARCH_URL: http://localhost:9200

dev:
  MAIN_ELASTIC_SEARCH_URL: https://search-main-4n3p5dmsencx7oqrf5p23qqocu.us-east-1.es.amazonaws.com
