openapi: 3.0.1

x-types:
  # DOESN'T WORK with APIGW (parser for yaml doesn't support "<<" merge syntax)
  - &APIGatewayIntegration
    type: "aws_proxy"
    httpMethod: "POST"
    timeoutInMillis: 29000
    credentials: ${main_api_role_arn}

info:
  version: 0.1
  title: Main REST API

paths:
  /user:
    get:
      description: Get User
      responses:
        200:
          description: A User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${get_user_invoke_arn}

    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{ 'statusCode': 200 }"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      responses:
        200:
          $ref: "#/components/responses/cors"

  /user/searchObject:
    get:
      description: Get Search Objects
      responses:
        200:
          description: Search Objects list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchObjectsList"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${get_search_objects_invoke_arn}

    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{ 'statusCode': 200 }"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      responses:
        200:
          $ref: "#/components/responses/cors"

  /user/searchObject/{index}:
    parameters:
      - $ref: "#/components/parameters/searchObjectIndex"

    put:
      description: Update SearchObject of a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSearchObjectRequestBody"
      responses:
        200:
          description: A SearchObject
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchObject"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${update_search_object_invoke_arn}

    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{ 'statusCode': 200 }"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      responses:
        200:
          $ref: "#/components/responses/cors"

  /search:
    post:
      description: Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequestBody"
      responses:
        200:
          description: Many SearchObjects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        400:
          $ref: "#/components/schemas/ErrorResponse"
        500:
          $ref: "#/components/schemas/ErrorResponse"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${search_endpoint_invoke_arn}

    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{ 'statusCode': 200 }"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      responses:
        200:
          $ref: "#/components/responses/cors"

  /user/payments/create-portal:
    post:
      description: Create payments portal session and return url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePaymentsPortalRequestBody"
      responses:
        200:
          description: Payments portal session url
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePaymentsPortalResponse"
        400:
          $ref: "#/components/schemas/ErrorResponse"
        500:
          $ref: "#/components/schemas/ErrorResponse"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${create_payments_portal_invoke_arn}

    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{ 'statusCode': 200 }"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      responses:
        200:
          $ref: "#/components/responses/cors"
  /stripe-escondido-webhook:
    post:
      description: StripeWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StripeWebhookRequestBody"
      responses:
        200:
          description: Acknowledge
        400:
          $ref: "#/components/schemas/ErrorResponse"
        500:
          $ref: "#/components/schemas/ErrorResponse"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${stripe_webhook_invoke_arn}

# ++++++++++++++++++
# + Generic config +

#x-amazon-apigateway-gateway-responses:
#  $ref: "./gateway-responses.yaml"

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true

x-amazon-apigateway-request-validator: all

# ++++++++++++++
# + COMPONENTS +
# ++++++++++++++

components:
  # +++++++++++
  # + SCHEMAS +
  schemas:
    ErrorResponse:
      description: Error processing the Request
      content:
        application/json:
          schema:
            type: object
            required:
              - error_code
              - error_message
            properties:
              error_code:
                type: string
              error_message:
                type: string

    UserId:
      type: string

    User:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UserId"

    SearchObjectIndex:
      type: number

    SearchObject:
      type: object
      properties:
        index:
          $ref: "#/components/schemas/SearchObjectIndex"

    SearchObjectsList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SearchObject"

    UpdateSearchObjectRequestBody:
      type: object
      required:
        - keyword
        - searchData
      properties:
        keyword:
          type: string
        searchData:
          type: object
          required:
            - twitter
          properties:
            twitter:
              requred:
                - enabledStatus
              properties:
                enabledStatus:
                  type: string
                  enum:
                    - DISABLED
                    - ENABLED

    SearchResult:
      type: object
      properties:
        id:
          type: string
        keyword:
          type: string
        happenedAt:
          type: string
        socialMedia:
          type: string

    SearchRequestBody:
      type: object
      required:
        - keyword
      properties:
        keyword:
          type: string
        pagination:
          $ref: "#/components/schemas/PaginationRequest"

    SearchResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SearchResult"
        pagination:
          $ref: "#/components/schemas/PaginationResponse"

    PaginationRequest:
      description: pagination request object
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer

    PaginationResponse:
      description: pagination response object
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer
        count:
          type: integer
        total:
          type: integer

    CreatePaymentsPortalRequestBody:
      description: portal session request object
      type: object
      required:
        - returnUrl
      properties:
        returnUrl:
          type: string

    CreatePaymentsPortalResponse:
      description: portal session response
      type: object
      required:
        - sessionUrl
      properties:
        sessionUrl:
          type: string

    StripeWebhookRequestBody:
      description: Event sent by Stripe
      type: object

  # ++++++++++++++
  # + PARAMETERS +
  parameters:
    searchObjectIndex:
      - name: index
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/SearchObjectIndex"

  # ++++++++++++++++++++
  # + SECURITY-SCHEMES +
  securitySchemes:
    cognitoPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - ${cognito_pool_auth_arn}

  # +++++++++++++
  # + RESPONSES +
  responses:
    cors:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Headers:
          schema:
            type: "string"
        Access-Control-Allow-Methods:
          schema:
            type: "string"
        Access-Control-Allow-Origin:
          schema:
            type: "string"
