openapi: 3.0.1

x-types:
  # DOESN'T WORK with APIGW (parser for yaml doesn't support "<<" merge syntax)
  - &APIGatewayIntegration
    type: "aws_proxy"
    httpMethod: "POST"
    timeoutInMillis: 29000
    credentials: ${main_api_role_arn}

info:
  version: 0.1
  title: Main REST API

paths:
  /user:
    get:
      description: Get User
      responses:
        200:
          description: A User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${get_user_invoke_arn}
  /user/searchObject/{index}:
    parameters:
      - $ref: "#/components/parameters/searchObjectIndex"
    put:
      description: Update SearchObject of a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSearchObjectRequestBody"
      responses:
        200:
          description: A SearchObject
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchObject"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${update_search_object_invoke_arn}
  /search:
    post:
      description: Search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequestBody"
      responses:
        200:
          description: Many SearchObjects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
      security:
        - cognitoPool: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        timeoutInMillis: 29000
        credentials: ${main_api_role_arn}
        uri: ${search_endpoint_invoke_arn}

# ++++++++++++++
# + COMPONENTS +
# ++++++++++++++

components:
  # +++++++++++
  # + SCHEMAS +
  schemas:
    UserId:
      type: string

    User:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UserId"

    SearchObjectIndex:
      type: number

    SearchObject:
      type: object
      properties:
        index:
          $ref: "#/components/schemas/SearchObjectIndex"

    UpdateSearchObjectRequestBody:
      type: object
      required:
        - keyword
        - searchData
      properties:
        keyword:
          type: string
        searchData:
          type: object
          required:
            - twitter
          properties:
            twitter:
              requred:
                - enabledStatus
              properties:
                enabledStatus:
                  type: string
                  enum:
                    - DISABLED
                    - ENABLED

    SearchResult:
      type: object
      properties:
        id:
          type: string
        keyword:
          type: string
        happenedAt:
          type: string
        socialMedia:
          type: string

    SearchRequestBody:
      type: object
      required:
        - keyword
      properties:
        keyword:
          type: string
        pagination:
          $ref: "#/components/schemas/PaginationRequest"

    SearchResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SearchResult"
          pagination:
            $ref: "#/components/schemas/PaginationResponse"

    PaginationRequest:
      description: pagination request object
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer

    PaginationResponse:
      description: pagination response object
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer
        count:
          type: integer
        total:
          type: integer

  # ++++++++++++++
  # + PARAMETERS +
  parameters:
    searchObjectIndex:
      - name: index
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/SearchObjectIndex"

  # ++++++++++++++++++++
  # + SECURITY-SCHEMES +
  securitySchemes:
    cognitoPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - ${cognito_pool_auth_arn}
