version: "3.8"
services:
  elasticsearch-local:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.0"
    container_name: elasticsearch-local
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
